services:
  frontend:
    build: ./frontend
    environment:
      API_URL: ${API_URL:-/benchmark}
    ports:
      - "8080:80"
    depends_on:
      - backend

  backend:
    build: ./backend
    ports:
      - "8050:5000"
    volumes:
      - ./backend/datos:/app/datos
      - ./backend/model_data:/app/model_data
      - ./frontend:/app/frontend
